// Bangladesh Divisions and Districts data

export const DIVISIONS = [
  "Dhaka",
  "Chittagong",
  "Rajshahi",
  "Khulna",
  "Barishal",
  "Sylhet",
  "Rangpur",
  "Mymensingh",
];

export const DISTRICTS = {
  Dhaka: [
    "Dhaka",
    "Gazipur",
    "Narayanganj",
    "Narsingdi",
    "Manikganj",
    "Munshiganj",
    "Kishoreganj",
    "Tangail",
    "Faridpur",
    "Rajbari",
    "Gopalganj",
    "Madaripur",
    "Shariatpur",
  ],
  Chittagong: [
    "Chittagong",
    "Cox's Bazar",
    "Feni",
    "Lakshmipur",
    "Comilla",
    "Chandpur",
    "Noakhali",
    "Brahmanbaria",
    "Khagrachhari",
    "Rangamati",
    "Bandarban",
  ],
  Rajshahi: [
    "Rajshahi",
    "Chapainawabganj",
    "Natore",
    "Naogaon",
    "Joypurhat",
    "Bogura",
    "Sirajganj",
    "Pabna",
  ],
  Khulna: [
    "Khulna",
    "Bagerhat",
    "Satkhira",
    "Jessore",
    "Narail",
    "Magura",
    "Jhenaidah",
    "Kushtia",
    "Chuadanga",
    "Meherpur",
  ],
  Barishal: [
    "Barishal",
    "Jhalokathi",
    "Pirojpur",
    "Bhola",
    "Patuakhali",
    "Barguna",
  ],
  Sylhet: [
    "Sylhet",
    "Moulvibazar",
    "Habiganj",
    "Sunamganj",
  ],
  Rangpur: [
    "Rangpur",
    "Dinajpur",
    "Gaibandha",
    "Nilphamari",
    "Kurigram",
    "Lalmonirhat",
    "Thakurgaon",
    "Panchagarh",
  ],
  Mymensingh: [
    "Mymensingh",
    "Netrokona",
    "Jamalpur",
    "Sherpur",
  ],
};
